 #(c) Copyright of George Oliver Cook, 5/12/2014. All Rights Resevered 
import time
import os
print("This is an adventure game. You do not use capitals, or puntuation. You must right the answers as they appear, for example 'Fight him.' you write 'fight him'. With these simple instructions you will go far,or not!")
time.sleep(1)
input("Press enter to start your story")
print("You are walking through a dark forest untill you come to an elf sitting in the road. You quickly dart in to a bush. The elf turns and looks your way.")
beast="Elrond"
print("'Hello?'")
time.sleep(1)
print("'Oh, I see you now.'")
time.sleep(1)
print("'What is your name?'")
name=input("Enter your name:")
time.sleep(1)
print("Hi there,", name, ", my name is", beast)
time.sleep(1)
waydh=input("What are you doing here, on an adventure or lost?")

if (waydh=="adventure"):
    print("Oh good, I love adventures!")
    time.sleep(1)
    direction1=input("Which way now, left or right?")
    if(direction1=="left"):
        print("Okay, to the left towards The Great Lake.")
        time.sleep(1)
        print("So you walked seveal miles to The Great Lake. But it does not go that smoothly.")
        time.sleep(1)
        print("Suddenly the ground shakes from the giant running towards you.")
        choice1=input("What do you want to do? Run the other way. Fight him. Run at him.")
        if (choice1=="run the other way"):
            print("You run the other way.")
            time.sleep(1)
            print("The giant is catching up...")
            time.sleep(1)
            print("The giant stood on you! Your adventure has come to an end.")
        elif (choice1=="fight him"):
            print("You draw your sword and you swing at his legs, making deep cuts.")
            time.sleep(3)
            print("But this does nothing. You stop and look for a weak spot. You spot a soft fleshy bit of skin, behind his knee cap.")
            time.sleep(3)
            print("You clamber up his leg, to the fleshy bit of skin and drive your sword in deep.")
            time.sleep(3)
            print("He falls to the ground, letting out an ear splitting scream.")
            time.sleep(3)
            print("After the death of the giant, you take his belongings, because he won't need them any more and carry on with your journey.")
            time.sleep(3)
            print("You walk a few more miles, it is getting dark now.")
            time.sleep(3)
            print("Eventually you get to The Great Lake; therefore you settle down for the night.")
            time.sleep(3)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("You hear a loud noise that startles you. You jump up, look around you, then you see it... A vampire!")
            time.sleep(1)
            choice2=input("You have to act fast. What do you do? Run in to the lake. Fight it.")
            if (choice2=="fight it"):
                print("The vampire is very close to you now so you draw and rasie you sword.")
                time.sleep(1)
                htkav=input("The vampire is with in arms reach, what do you do? Stab it in the face. Stab it in the heart.")
                if (htkav=="stab it in the face"):
                    print("You attempt does nothing; and the vampire drinks you blood.")
                    time.sleep(1)
                    print("Your adventure has come to an end.")
                elif (htkav=="stab it in the heart"):
                    print("You stab it though the heart.")
                    time.sleep(1)
                    print("Suddenly the vampire bursts in to a ball of blinding light")
                    time.sleep(1)
                    print("You shut your eyes untill Elrond taps you on the shoulder.")
                    time.sleep(1)
                    print("'Yes?' you say in return.")
                    time.sleep(1)
                    print("'Get up!' he says 'We have a long day ahead of us.'")
                    time.sleep(1)
                    print("You get up and walk around the lake.")
                    time.sleep(1)
                    print("You walk the rest of that day.")
                    time.sleep(1)
                    print("And the next day.")
                    time.sleep(1)
                    print("And the day after that.")
                    time.sleep(1)
                    print("You stop when you come to a sleeping wolf.")
                    time.sleep(1)
                    choice3=input("There is a sleeping wolf infront of you and just enough room to go around him. What do you do? Try and walk around him. Stab him in his sleep.")
                    if (choice3=="try and walk around him"):
                        print("He hears the shuffling of your feet and wakes up.")
                        time.sleep(1)
                        print("You freeze! But it is no luck, he bares his teeth, opens his mouth and rips you face off!")
                        time.sleep(1)
                        print("Your adventure has come to an end.")
                    elif (choice3=="stab him in his sleep"):
                        print("You draw your sword and bring it down on his neck, his head comes clean off and rolls along the floor for a little while, blood trailing after it.")
                        time.sleep(1)
                        os.system('cls')
                        print("After the third battle you walk for five days untill you get to a temple. The temple is tall, with pillars running each side.")
                        time.sleep(1)
                        print("You walk up to the door, but it does not open instead a voice sounds.")
                        time.sleep(1)
                        print("What has roots as nobody sees, Is taller than trees, Up, up it goes, And yet never grows?")
                        riddle1=input("Do you know the answer?")
                        if (riddle1=="mountain"):
                            print("The door opens, you walk forward to another door. A voice sounds again.")
                            time.sleep(1)
                            print("It cannot be seen, cannot be felt, Cannot be heard, cannot be smelt. It lies behind stars and under hills, And empty holes it fills. It comes first and follows after, Ends life, kills laughter.")
                            riddle2=input("Do you know the answer?")
                            if (riddle2=="dark"):
                                print("The door opens, you walk forward to another door. A voice sounds again.")
                                time.sleep(1)
                                print("You defeated three things so far, that is enough to make a triagram.")
                                triagram1=input("Can you work out the triagram...?")
                                if (triagram1=="gvw"):
                                    print("The door opens to reveal behind it a mountain load of treasure.")
                                    time.sleep(1)
                                    print("You and Elrond run in and grab what you want.")
                                    time.sleep(1)
                                    print("You come out with armfuls; and start to walk home")
                                    time.sleep(1)
                                    print("You have completed The Great Lake adventure!")
                                else:
                                    print("You here a cracking sound. Then a boulder falls down on top of you.")
                                    time.sleep(1)
                                    print("Your adventure has come to an end.")
                                    
                            else:
                                print("You here a cracking sound. Then a boulder falls down on top of you.")
                                time.sleep(1)
                                print("Your adventure has come to an end.")
                        else:
                            print("You here a cracking sound. Then a boulder falls down on top of you.")
                            time.sleep(1)
                            print("Your adventure has come to an end.")
                               
            elif(choice2=="run in to the lake"):
                print("You dart in to the lake.")
                time.sleep(1)
                print("A giant crab jumps up out of the water and pulls you under. This results in you drowning")
                time.sleep(1)
                print("Your adventure has come to an end.")
        elif (choice1=="run at him"):
            print("You run at him. Shouting your war cry, 'Arrrrrrrrgh!'")
            time.sleep(1)
            print("The Giant gets confused and panics, in the commotion you get a foot to the back and are shot in to a neighboring tree. SPLAT!!")
            time.sleep(1)
            print("Your adventure has come to an end!")
            

    elif (direction1=="right"):
        print("Okay, to the right towards Belzin forest")
        time.sleep(1)
        print("You start your journey to the Belzin forest")
        movement=input("Do you, run, or walk.")
        if (movement=="walk"):
            print("You have made a sensible decision; and slowly make your way to the Belzin forest")
            time.sleep(1)
            print("You have walked for several days and food has run out.")
            time.sleep(1)
            print("You see two bushes, one with yellow berries, the other with dark green berries.")
            eat1=input("Which one do you choose? Yellow. Green.")
            if (eat1=="yellow"):
                print("You walk up to the bush with yellow berries.")
                time.sleep(1)
                print("You take a handful of yellow berries and put them in to your mouth...")
                time.sleep(3)
                print("You have eaten the right berries and carry on with your journey.")
                time.sleep(1)
                print("You open your sack and start filling it with berries.")
                time.sleep(2)
                print("You hear a noise...")
                time.sleep(2)
                print("The bush starts to shake...")
                time.sleep(2)
                print("A big fluffy bunny with red eyes crawls out from the bush.")
                bunny1=input("What do you do? Run away. Stay and ignore the bunny.")
                if (bunny1=="run away"):
                    print("You run as fast as you can towards the end of the forest")
                    time.sleep(3)
                    print("You have escaped the bunny!")
                    time.sleep(1)
                    print("You start to slow down and gradualy come to a slow but sure walk")
                    time.sleep(2)
                    print("You walk for several days.")
                    time.sleep(1)
                    print("Untill you come to a river.")
                    river1=input("What do you do? Go through the river. Build a bridge. Jump over.")
                    if(river1=="go through the river"):
                        print("You walk towards the river")
                        time.sleep(1)
                        print("Pull up your socks and wade in.")
                        time.sleep(3)
                        print("The water is cold, but you carry on going.")
                        time.sleep(3)
                        print("Eventually you get to the other side.")
                        time.sleep(3)
                        print("After the river you carry on walking untill you get to grass land.")
                        time.sleep(3)
                        print("Suddenly you come to a crack in the ground. You can not see the bottom, but you can see something running down the side of the hole.")
                        crack1=input("What do you do? Jump over the crack. Go down the crack. Give up all hope.")
                        if (crack1=="go down the crack"):
                            print("You lay on the ground, shuffle up to the crack and look down it.")
                            time.sleep(3)
                            print("The thing you saw was a ladder.")
                            time.sleep(3)
                            print("You grab it and swing yourself on to it.")
                            time.sleep(3)
                            print("You start to climb down the ladder...")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("Untill you get to the bottom.")
                            time.sleep(3)
                            print("At the bottom you find...")
                            time.sleep(3)
                            os.system('cls')
                            maths1=input("This carved in to stone, 'If x=4, then what is y, 7x+3y=55' y=")
                            if (maths1=="7"):
                                print("The stone gives way, just enough for you to walk past it.")
                                time.sleep(3)
                                print("You walk past it.")
                                time.sleep(3)
                                print("But there is another stone.")
                                time.sleep(3)
                                print("and it says, 'You have come so far, but do you remember the way you came?'")
                                directionriddle=input("At the start of this adventure which way did you go? Left. Right. Straight on.")
                                if (directionriddle=="right"):
                                      print("The stone gives way completely, to reveal the tomb of your family.")
                                      time.sleep(3)
                                      print("You walk in and sit down making yourself comfortable.")
                                      time.sleep(3)
                                      print("You get up again and walk over to a coffin.")
                                      time.sleep(3)
                                      print("The plaque on it says, '",name,"Palm'")
                                      time.sleep(3)
                                      print("'I am named after my great father.' you say.")
                                      time.sleep(3)
                                      print("You smile.")
                                      time.sleep(3)
                                      print("Then you put you hand on his coffin...")
                                      time.sleep(3)
                                      print("A great flash of light surrounds you...")
                                      time.sleep(3)
                                      print("You close your eyes...")
                                      time.sleep(3)
                                      print("You feel like you are falling.")
                                      time.sleep(1)
                                      print("Faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("Untill you suddenly stop an inch of the ground.")
                                      time.sleep(3)
                                      print("You have joined the after life.")
                                      time.sleep(1)
                                      print("To be continued.")
                                else:
                                      print("You hear a creaking sound...")
                                      time.sleep(3)
                                      print("Suddenly a massive body of water comes rushing towards you.")
                                      time.sleep(3)
                                      print("The water fills the whole crack and you drown!")
                                      time.sleep(1)
                                      print("Your adventure has come to an end")    
                                
                                
                            else:
                                print("You hear a creaking sound...")
                                time.sleep(3)
                                print("Suddenly a massive body of water comes rushing towards you.")
                                time.sleep(3)
                                print("The water fills the whole crack and you drown!")
                                time.sleep(1)
                                print("Your adventure has come to an end")
                        elif (crack1=="jump over crack"):
                            print("You stand on the edge of the crack and jump...")
                            time.sleep(3)
                            print("You don't jump far enough...")
                            time.sleep(3)
                            print("You land on the edge of the crack, slip and fall down it.")
                            time.sleep(1)
                            print("Your adventure has come to an end")
                        elif (crack1=="give up all hope"):
                            print("You sit down on the ground and do nothing.")
                            time.sleep(3)
                            print("Then you feel a sharp pain in your back.")
                            time.sleep(3)
                            print("You turn around to find the bunny ripping bits of flesh from your body.")
                            time.sleep(3)
                            print("You faint...")
                            time.sleep(3)
                            print("Fall down the crack and break every bone inyour body.")
                            time.sleep(1)
                            print("Your adventure has come to an end")
                    elif (river1=="build a bridge"):
                        print("The only wood around you is the trees.")
                        time.sleep(1)
                        print("So you start to chop down a tree with your axe...")
                        time.sleep(3)
                        print("You misjudge the height and weight of the tree.")
                        time.sleep(3)
                        print("It starts to fall over!")
                        time.sleep(3)
                        print("You don't get out of the way in time and the tree squashes you.")
                        time.sleep(1)
                        print("Your adventure has come to an end")
                    elif (river1=="jump over it"):
                        print("You walk back a bit.")
                        time.sleep(1)
                        print("Then stop, turn around and start to run towards the river.")
                        time.sleep(3)
                        print("You are runnung at full pace...")
                        time.sleep(3)
                        print("You jump!")
                        time.sleep(3)
                        print("You land on the sandy, other side of the river.")
                        time.sleep(3)
                        print("Because of the loose terrian, you slip and impale your head on a rock.")
                        time.sleep(1)
                        print("Your adventure has come to an end")
                elif (bunny1=="stay and ignore the bunny"):
                    print("You ignore the bunny and carry on filling your sack.")
                    time.sleep(3)
                    print("You feel a pain in your leg...")
                    time.sleep(3)
                    print("You look down to see the bunny munching on your leg.")
                    time.sleep(1)
                    print("You stab the bunny...")
                    time.sleep(1)
                    print("Its head falls off, but you still have a pain in your leg.")
                    time.sleep(1)
                    print("You finish collecting the berries and carry on walking")
                    time.sleep(3)
                    print("You walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("Untill you see the place you have been looking for.")
                    time.sleep(3)
                    print("Suddenly...")
                    time.sleep(3)
                    print("You fall down dead")
                    time.sleep(1)
                    print("Your adventure has come to an end")
            elif (eat1=="green"):
                print("You walk up to the bush with green berries.")
                time.sleep(1)
                print("You take a handful of green berries and put them in to your mouth...")
                time.sleep(3)
                print("You have eaten the wrong berries and fall down dead.")
                time.sleep(1)
                print("Your adventure has come to an end!")
        elif (movement=="run"):
            print("You start to run...")
            time.sleep(3)
            print("You trip and scrape your face off.")
            time.sleep(1)
            print("Your adventure has come to an end!")
        

    else:
        print("Uh, good bye!")

elif (waydh=="on an adventure"):
    print("Oh good, I love adventures!")
    time.sleep(1)
    direction1=input("Which way now, left or right?")
    if(direction1=="left"):
        print("Okay, to the left towards The Great Lake.")
        time.sleep(1)
        print("So you walked seveal miles to The Great Lake. But it does not go that smoothly.")
        time.sleep(1)
        print("Suddenly the ground shakes from the giant running towards you.")
        choice1=input("What do you want to do? Run the other way. Fight him. Run at him.")
        if (choice1=="run the other way"):
            print("You run the other way.")
            time.sleep(1)
            print("The giant is catching up...")
            time.sleep(1)
            print("The giant stood on you! Your adventure has come to an end.")
        elif (choice1=="fight him"):
            print("You draw your sword and you swing at his legs, making deep cuts.")
            time.sleep(3)
            print("But this does nothing. You stop and look for a weak spot. You spot a soft fleshy bit of skin, behind his knee cap.")
            time.sleep(3)
            print("You clamber up his leg, to the fleshy bit of skin and drive your sword in deep.")
            time.sleep(3)
            print("He falls to the ground, letting out an ear splitting scream.")
            time.sleep(3)
            print("After the death of the giant, you take his belongings, because he won't need them any more and carry on with your journey.")
            time.sleep(3)
            print("You walk a few more miles, it is getting dark now.")
            time.sleep(3)
            print("Eventually you get to The Great Lake; therefore you settle down for the night.")
            time.sleep(3)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("You hear a loud noise that startles you. You jump up, look around you, then you see it... A vampire!")
            time.sleep(1)
            choice2=input("You have to act fast. What do you do? Run in to the lake. Fight it.")
            if (choice2=="fight it"):
                print("The vampire is very close to you now so you draw and rasie you sword.")
                time.sleep(1)
                htkav=input("The vampire is with in arms reach, what do you do? Stab it in the face. Stab it in the heart.")
                if (htkav=="stab it in the face"):
                    print("You attempt does nothing; and the vampire drinks you blood.")
                    time.sleep(1)
                    print("Your adventure has come to an end.")
                elif (htkav=="stab it in the heart"):
                    print("You stab it though the heart.")
                    time.sleep(1)
                    print("Suddenly the vampire bursts in to a ball of blinding light")
                    time.sleep(1)
                    print("You shut your eyes untill Elrond taps you on the shoulder.")
                    time.sleep(1)
                    print("'Yes?' you say in return.")
                    time.sleep(1)
                    print("'Get up!' he says 'We have a long day ahead of us.'")
                    time.sleep(1)
                    print("You get up and walk around the lake.")
                    time.sleep(1)
                    print("You walk the rest of that day.")
                    time.sleep(1)
                    print("And the next day.")
                    time.sleep(1)
                    print("And the day after that.")
                    time.sleep(1)
                    print("You stop when you come to a sleeping wolf.")
                    time.sleep(1)
                    choice3=input("There is a sleeping wolf infront of you and just enough room to go around him. What do you do? Try and walk around him. Stab him in his sleep.")
                    if (choice3=="try and walk around him"):
                        print("He hears the shuffling of your feet and wakes up.")
                        time.sleep(1)
                        print("You freeze! But it is no luck, he bares his teeth, opens his mouth and rips you face off!")
                        time.sleep(1)
                        print("Your adventure has come to an end.")
                    elif (choice3=="stab him in his sleep"):
                        print("You draw your sword and bring it down on his neck, his head comes clean off and rolls along the floor for a little while, blood trailing after it.")
                        time.sleep(1)
                        os.system('cls')
                        print("After the third battle you walk for five days untill you get to a temple. The temple is tall, with pillars running each side.")
                        time.sleep(1)
                        print("You walk up to the door, but it does not open instead a voice sounds.")
                        time.sleep(1)
                        print("What has roots as nobody sees, Is taller than trees, Up, up it goes, And yet never grows?")
                        riddle1=input("Do you know the answer?")
                        if (riddle1=="mountain"):
                            print("The door opens, you walk forward to another door. A voice sounds again.")
                            time.sleep(1)
                            print("It cannot be seen, cannot be felt, Cannot be heard, cannot be smelt. It lies behind stars and under hills, And empty holes it fills. It comes first and follows after, Ends life, kills laughter.")
                            riddle2=input("Do you know the answer?")
                            if (riddle2=="dark"):
                                print("The door opens, you walk forward to another door. A voice sounds again.")
                                time.sleep(1)
                                print("You defeated three things so far, that is enough to make a triagram.")
                                triagram1=input("Can you work out the triagram...?")
                                if (triagram1=="gvw"):
                                    print("The door opens to reveal behind it a mountain load of treasure.")
                                    time.sleep(1)
                                    print("You and Elrond run in and grab what you want.")
                                    time.sleep(1)
                                    print("You come out with armfuls; and start to walk home")
                                    time.sleep(1)
                                    print("You have completed The Great Lake adventure!")
                                else:
                                    print("You here a cracking sound. Then a boulder falls down on top of you.")
                                    time.sleep(1)
                                    print("Your adventure has come to an end.")
                                    
                            else:
                                print("You here a cracking sound. Then a boulder falls down on top of you.")
                                time.sleep(1)
                                print("Your adventure has come to an end.")
                        else:
                            print("You here a cracking sound. Then a boulder falls down on top of you.")
                            time.sleep(1)
                            print("Your adventure has come to an end.")
                               
            elif(choice2=="run in to the lake"):
                print("You dart in to the lake.")
                time.sleep(1)
                print("A giant crab jumps up out of the water and pulls you under. This results in you drowning")
                time.sleep(1)
                print("Your adventure has come to an end.")
        elif (choice1=="run at him"):
            print("You run at him. Shouting your war cry, 'Arrrrrrrrgh!'")
            time.sleep(1)
            print("The Giant gets confused and panics, in the commotion you get a foot to the back and are shot in to a neighboring tree. SPLAT!!")
            time.sleep(1)
            print("Your adventure has come to an end!")
            

    elif (direction1=="right"):
        print("Okay, to the right towards Belzin forest")
        time.sleep(1)
        print("You start your journey to the Belzin forest")
        movement=input("Do you, run, or walk.")
        if (movement=="walk"):
            print("You have made a sensible decision; and slowly make your way to the Belzin forest")
            time.sleep(1)
            print("You have walked for several days and food has run out.")
            time.sleep(1)
            print("You see two bushes, one with yellow berries, the other with dark green berries.")
            eat1=input("Which one do you choose? Yellow. Green.")
            if (eat1=="yellow"):
                print("You walk up to the bush with yellow berries.")
                time.sleep(1)
                print("You take a handful of yellow berries and put them in to your mouth...")
                time.sleep(3)
                print("You have eaten the right berries and carry on with your journey.")
                time.sleep(1)
                print("You open your sack and start filling it with berries.")
                time.sleep(2)
                print("You hear a noise...")
                time.sleep(2)
                print("The bush starts to shake...")
                time.sleep(2)
                print("A big fluffy bunny with red eyes crawls out from the bush.")
                bunny1=input("What do you do? Run away. Stay and ignore the bunny.")
                if (bunny1=="run away"):
                    print("You run as fast as you can towards the end of the forest")
                    time.sleep(3)
                    print("You have escaped the bunny!")
                    time.sleep(1)
                    print("You start to slow down and gradualy come to a slow but sure walk")
                    time.sleep(2)
                    print("You walk for several days.")
                    time.sleep(1)
                    print("Untill you come to a river.")
                    river1=("What do you do? Go through the river. Build a bridge. Jump over.")
                    if(river1=="go through the river"):
                        print("You walk towards the river")
                        time.sleep(1)
                        print("Pull up your socks and wade in.")
                        time.sleep(3)
                        print("The water is cold, but you carry on going.")
                        time.sleep(3)
                        print("Eventually you get to the other side.")
                        time.sleep(3)
                        print("After the river you carry on walking untill you get to grass land.")
                        time.sleep(3)
                        print("Suddenly you come to a crack in the ground. You can not see the bottom, but you can see something running down the side of the hole.")
                        crack1=input("What do you do? Jump over the crack. Go down the crack. Give up all hope.")
                        if (crack1=="go down the crack"):
                            print("You lay on the ground, shuffle up to the crack and look down it.")
                            time.sleep(3)
                            print("The thing you saw was a ladder.")
                            time.sleep(3)
                            print("You grab it and swing yourself on to it.")
                            time.sleep(3)
                            print("You start to climb down the ladder...")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("Untill you get to the bottom.")
                            time.sleep(3)
                            print("At the bottom you find...")
                            time.sleep(3)
                            os.system('cls')
                            maths1=input("This carved in to stone, 'If x=4, then what is y, 7x+3y=55' y=")
                            if (maths1=="7"):
                                print("The stone gives way, just enough for you to walk past it.")
                                time.sleep(3)
                                print("You walk past it.")
                                time.sleep(3)
                                print("But there is another stone.")
                                time.sleep(3)
                                print("and it says, 'You have come so far, but do you remember the way you came?'")
                                directionriddle=input("At the start of this adventure which way did you go? Left. Right. Straight on.")
                                if (directionriddle=="right"):
                                      print("The stone gives way completely, to reveal the tomb of your family.")
                                      time.sleep(3)
                                      print("You walk in and sit down making yourself comfortable.")
                                      time.sleep(3)
                                      print("You get up again and walk over to a coffin.")
                                      time.sleep(3)
                                      print("The plaque on it says, '",name,"Palm'")
                                      time.sleep(3)
                                      print("'I am named after my great father.' you say.")
                                      time.sleep(3)
                                      print("You smile.")
                                      time.sleep(3)
                                      print("Then you put you hand on his coffin...")
                                      time.sleep(3)
                                      print("A great flash of light surrounds you...")
                                      time.sleep(3)
                                      print("You close your eyes...")
                                      time.sleep(3)
                                      print("You feel like you are falling.")
                                      time.sleep(1)
                                      print("Faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("Untill you suddenly stop an inch of the ground.")
                                      time.sleep(3)
                                      print("You have joined the after life.")
                                      time.sleep(1)
                                      print("To be continued.")
                                else:
                                    print("You hear a creaking sound...")
                                    time.sleep(3)
                                    print("Suddenly a massive body of water comes rushing towards you.")
                                    time.sleep(3)
                                    print("The water fills the whole crack and you drown!")
                                    time.sleep(1)
                                    print("Your adventure has come to an end")    
                                
                                
                            else:
                                print("You hear a creaking sound...")
                                time.sleep(3)
                                print("Suddenly a massive body of water comes rushing towards you.")
                                time.sleep(3)
                                print("The water fills the whole crack and you drown!")
                                time.sleep(1)
                                print("Your adventure has come to an end")
                        elif (crack1=="jump over crack"):
                            print("You stand on the edge of the crack and jump...")
                            time.sleep(3)
                            print("You don't jump far enough...")
                            time.sleep(3)
                            print("You land on the edge of the crack, slip and fall down it.")
                            time.sleep(1)
                            print("Your adventure has come to an end")
                        elif (crack1=="give up all hope"):
                            print("You sit down on the ground and do nothing.")
                            time.sleep(3)
                            print("Then you feel a sharp pain in your back.")
                            time.sleep(3)
                            print("You turn around to find the bunny ripping bits of flesh from your body.")
                            time.sleep(3)
                            print("You faint...")
                            time.sleep(3)
                            print("Fall down the crack and break every bone inyour body.")
                            time.sleep(1)
                            print("Your adventure has come to an end")
                    elif (river1=="build a bridge"):
                        print("The only wood around you is the trees.")
                        time.sleep(1)
                        print("So you start to chop down a tree with your axe...")
                        time.sleep(3)
                        print("You misjudge the height and weight of the tree.")
                        time.sleep(3)
                        print("It starts to fall over!")
                        time.sleep(3)
                        print("You don't get out of the way in time and the tree squashes you.")
                        time.sleep(1)
                        print("Your adventure has come to an end")
                    elif (river1=="jump over it"):
                        print("You walk back a bit.")
                        time.sleep(1)
                        print("Then stop, turn around and start to run towards the river.")
                        time.sleep(3)
                        print("You are runnung at full pace...")
                        time.sleep(3)
                        print("You jump!")
                        time.sleep(3)
                        print("You land on the sandy, other side of the river.")
                        time.sleep(3)
                        print("Because of the loose terrian, you slip and impale your head on a rock.")
                        time.sleep(1)
                        print("Your adventure has come to an end")
                elif (bunny1=="stay and ignore the bunny"):
                    print("You ignore the bunny and carry on filling your sack.")
                    time.sleep(3)
                    print("You feel a pain in your leg...")
                    time.sleep(3)
                    print("You look down to see the bunny munching on your leg.")
                    time.sleep(1)
                    print("You stab the bunny...")
                    time.sleep(1)
                    print("Its head falls off, but you still have a pain in your leg.")
                    time.sleep(1)
                    print("You finish collecting the berries and carry on walking")
                    time.sleep(3)
                    print("You walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("Untill you see the place you have been looking for.")
                    time.sleep(3)
                    print("Suddenly...")
                    time.sleep(3)
                    print("You fall down dead")
                    time.sleep(1)
                    print("Your adventure has come to an end")
            elif (eat1=="green"):
                print("You walk up to the bush with green berries.")
                time.sleep(1)
                print("You take a handful of green berries and put them in to your mouth...")
                time.sleep(3)
                print("You have eaten the wrong berries and fall down dead.")
                time.sleep(1)
                print("Your adventure has come to an end!")
        elif (movement=="run"):
            print("You start to run...")
            time.sleep(3)
            print("You trip and scrape your face off.")
            time.sleep(1)
            print("Your adventure has come to an end!")

elif (waydh=="an adventure"):
    print("Oh good, I love adventures!")
    time.sleep(1)
    direction1=input("Which way now, left or right?")
    if(direction1=="left"):
        print("Okay, to the left towards The Great Lake.")
        time.sleep(1)
        print("So you walked seveal miles to The Great Lake. But it does not go that smoothly.")
        time.sleep(1)
        print("Suddenly the ground shakes from the giant running towards you.")
        choice1=input("What do you want to do? Run the other way. Fight him. Run at him.")
        if (choice1=="run the other way"):
            print("You run the other way.")
            time.sleep(1)
            print("The giant is catching up...")
            time.sleep(1)
            print("The giant stood on you! Your adventure has come to an end.")
        elif (choice1=="fight him"):
            print("You draw your sword and you swing at his legs, making deep cuts.")
            time.sleep(3)
            print("But this does nothing. You stop and look for a weak spot. You spot a soft fleshy bit of skin, behind his knee cap.")
            time.sleep(3)
            print("You clamber up his leg, to the fleshy bit of skin and drive your sword in deep.")
            time.sleep(3)
            print("He falls to the ground, letting out an ear splitting scream.")
            time.sleep(3)
            print("After the death of the giant, you take his belongings, because he won't need them any more and carry on with your journey.")
            time.sleep(3)
            print("You walk a few more miles, it is getting dark now.")
            time.sleep(3)
            print("Eventually you get to The Great Lake; therefore you settle down for the night.")
            time.sleep(3)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("You hear a loud noise that startles you. You jump up, look around you, then you see it... A vampire!")
            time.sleep(1)
            choice2=input("You have to act fast. What do you do? Run in to the lake. Fight it.")
            if (choice2=="fight it"):
                print("The vampire is very close to you now so you draw and rasie you sword.")
                time.sleep(1)
                htkav=input("The vampire is with in arms reach, what do you do? Stab it in the face. Stab it in the heart.")
                if (htkav=="stab it in the face"):
                    print("You attempt does nothing; and the vampire drinks you blood.")
                    time.sleep(1)
                    print("Your adventure has come to an end.")
                elif (htkav=="stab it in the heart"):
                    print("You stab it though the heart.")
                    time.sleep(1)
                    print("Suddenly the vampire bursts in to a ball of blinding light")
                    time.sleep(1)
                    print("You shut your eyes untill Elrond taps you on the shoulder.")
                    time.sleep(1)
                    print("'Yes?' you say in return.")
                    time.sleep(1)
                    print("'Get up!' he says 'We have a long day ahead of us.'")
                    time.sleep(1)
                    print("You get up and walk around the lake.")
                    time.sleep(1)
                    print("You walk the rest of that day.")
                    time.sleep(1)
                    print("And the next day.")
                    time.sleep(1)
                    print("And the day after that.")
                    time.sleep(1)
                    print("You stop when you come to a sleeping wolf.")
                    time.sleep(1)
                    choice3=input("There is a sleeping wolf infront of you and just enough room to go around him. What do you do? Try and walk around him. Stab him in his sleep.")
                    if (choice3=="try and walk around him"):
                        print("He hears the shuffling of your feet and wakes up.")
                        time.sleep(1)
                        print("You freeze! But it is no luck, he bares his teeth, opens his mouth and rips you face off!")
                        time.sleep(1)
                        print("Your adventure has come to an end.")
                    elif (choice3=="stab him in his sleep"):
                        print("You draw your sword and bring it down on his neck, his head comes clean off and rolls along the floor for a little while, blood trailing after it.")
                        time.sleep(1)
                        os.system('cls')
                        print("After the third battle you walk for five days untill you get to a temple. The temple is tall, with pillars running each side.")
                        time.sleep(1)
                        print("You walk up to the door, but it does not open instead a voice sounds.")
                        time.sleep(1)
                        print("What has roots as nobody sees, Is taller than trees, Up, up it goes, And yet never grows?")
                        riddle1=input("Do you know the answer?")
                        if (riddle1=="mountain"):
                            print("The door opens, you walk forward to another door. A voice sounds again.")
                            time.sleep(1)
                            print("It cannot be seen, cannot be felt, Cannot be heard, cannot be smelt. It lies behind stars and under hills, And empty holes it fills. It comes first and follows after, Ends life, kills laughter.")
                            riddle2=input("Do you know the answer?")
                            if (riddle2=="dark"):
                                print("The door opens, you walk forward to another door. A voice sounds again.")
                                time.sleep(1)
                                print("You defeated three things so far, that is enough to make a triagram.")
                                triagram1=input("Can you work out the triagram...?")
                                if (triagram1=="gvw"):
                                    print("The door opens to reveal behind it a mountain load of treasure.")
                                    time.sleep(1)
                                    print("You and Elrond run in and grab what you want.")
                                    time.sleep(1)
                                    print("You come out with armfuls; and start to walk home")
                                    time.sleep(1)
                                    print("You have completed The Great Lake adventure!")
                                else:
                                    print("You here a cracking sound. Then a boulder falls down on top of you.")
                                    time.sleep(1)
                                    print("Your adventure has come to an end.")
                                    
                            else:
                                print("You here a cracking sound. Then a boulder falls down on top of you.")
                                time.sleep(1)
                                print("Your adventure has come to an end.")
                        else:
                            print("You here a cracking sound. Then a boulder falls down on top of you.")
                            time.sleep(1)
                            print("Your adventure has come to an end.")
                               
            elif(choice2=="run in to the lake"):
                print("You dart in to the lake.")
                time.sleep(1)
                print("A giant crab jumps up out of the water and pulls you under. This results in you drowning")
                time.sleep(1)
                print("Your adventure has come to an end.")
        elif (choice1=="run at him"):
            print("You run at him. Shouting your war cry, 'Arrrrrrrrgh!'")
            time.sleep(1)
            print("The Giant gets confused and panics, in the commotion you get a foot to the back and are shot in to a neighboring tree. SPLAT!!")
            time.sleep(1)
            print("Your adventure has come to an end!")
            

    elif (direction1=="right"):
        print("Okay, to the right towards Belzin forest")
        time.sleep(1)
        print("You start your journey to the Belzin forest")
        movement=input("Do you, run, or walk.")
        if (movement=="walk"):
            print("You have made a sensible decision; and slowly make your way to the Belzin forest")
            time.sleep(1)
            print("You have walked for several days and food has run out.")
            time.sleep(1)
            print("You see two bushes, one with yellow berries, the other with dark green berries.")
            eat1=input("Which one do you choose? Yellow. Green.")
            if (eat1=="yellow"):
                print("You walk up to the bush with yellow berries.")
                time.sleep(1)
                print("You take a handful of yellow berries and put them in to your mouth...")
                time.sleep(3)
                print("You have eaten the right berries and carry on with your journey.")
                time.sleep(1)
                print("You open your sack and start filling it with berries.")
                time.sleep(2)
                print("You hear a noise...")
                time.sleep(2)
                print("The bush starts to shake...")
                time.sleep(2)
                print("A big fluffy bunny with red eyes crawls out from the bush.")
                bunny1=input("What do you do? Run away. Stay and ignore the bunny.")
                if (bunny1=="run away"):
                    print("You run as fast as you can towards the end of the forest")
                    time.sleep(3)
                    print("You have escaped the bunny!")
                    time.sleep(1)
                    print("You start to slow down and gradualy come to a slow but sure walk")
                    time.sleep(2)
                    print("You walk for several days.")
                    time.sleep(1)
                    print("Untill you come to a river.")
                    river1=("What do you do? Go through the river. Build a bridge. Jump over.")
                    if(river1=="go through the river"):
                        print("You walk towards the river")
                        time.sleep(1)
                        print("Pull up your socks and wade in.")
                        time.sleep(3)
                        print("The water is cold, but you carry on going.")
                        time.sleep(3)
                        print("Eventually you get to the other side.")
                        time.sleep(3)
                        print("After the river you carry on walking untill you get to grass land.")
                        time.sleep(3)
                        print("Suddenly you come to a crack in the ground. You can not see the bottom, but you can see something running down the side of the hole.")
                        crack1=input("What do you do? Jump over the crack. Go down the crack. Give up all hope.")
                        if (crack1=="go down the crack"):
                            print("You lay on the ground, shuffle up to the crack and look down it.")
                            time.sleep(3)
                            print("The thing you saw was a ladder.")
                            time.sleep(3)
                            print("You grab it and swing yourself on to it.")
                            time.sleep(3)
                            print("You start to climb down the ladder...")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("Untill you get to the bottom.")
                            time.sleep(3)
                            print("At the bottom you find...")
                            time.sleep(3)
                            os.system('cls')
                            maths1=input("This carved in to stone, 'If x=4, then what is y, 7x+3y=55' y=")
                            if (maths1=="7"):
                                print("The stone gives way, just enough for you to walk past it.")
                                time.sleep(3)
                                print("You walk past it.")
                                time.sleep(3)
                                print("But there is another stone.")
                                time.sleep(3)
                                print("and it says, 'You have come so far, but do you remember the way you came?'")
                                directionriddle=input("At the start of this adventure which way did you go? Left. Right. Straight on.")
                                if (directionriddle=="right"):
                                      print("The stone gives way completely, to reveal the tomb of your family.")
                                      time.sleep(3)
                                      print("You walk in and sit down making yourself comfortable.")
                                      time.sleep(3)
                                      print("You get up again and walk over to a coffin.")
                                      time.sleep(3)
                                      print("The plaque on it says, '",name,"Palm'")
                                      time.sleep(3)
                                      print("'I am named after my great father.' you say.")
                                      time.sleep(3)
                                      print("You smile.")
                                      time.sleep(3)
                                      print("Then you put you hand on his coffin...")
                                      time.sleep(3)
                                      print("A great flash of light surrounds you...")
                                      time.sleep(3)
                                      print("You close your eyes...")
                                      time.sleep(3)
                                      print("You feel like you are falling.")
                                      time.sleep(1)
                                      print("Faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("Untill you suddenly stop an inch of the ground.")
                                      time.sleep(3)
                                      print("You have joined the after life.")
                                      time.sleep(1)
                                      print("To be continued.")
                                else:
                                    print("You hear a creaking sound...")
                                    time.sleep(3)
                                    print("Suddenly a massive body of water comes rushing towards you.")
                                    time.sleep(3)
                                    print("The water fills the whole crack and you drown!")
                                    time.sleep(1)
                                    print("Your adventure has come to an end")    
                                
                                
                            else:
                                print("You hear a creaking sound...")
                                time.sleep(3)
                                print("Suddenly a massive body of water comes rushing towards you.")
                                time.sleep(3)
                                print("The water fills the whole crack and you drown!")
                                time.sleep(1)
                                print("Your adventure has come to an end")
                        elif (crack1=="jump over crack"):
                            print("You stand on the edge of the crack and jump...")
                            time.sleep(3)
                            print("You don't jump far enough...")
                            time.sleep(3)
                            print("You land on the edge of the crack, slip and fall down it.")
                            time.sleep(1)
                            print("Your adventure has come to an end")
                        elif (crack1=="give up all hope"):
                            print("You sit down on the ground and do nothing.")
                            time.sleep(3)
                            print("Then you feel a sharp pain in your back.")
                            time.sleep(3)
                            print("You turn around to find the bunny ripping bits of flesh from your body.")
                            time.sleep(3)
                            print("You faint...")
                            time.sleep(3)
                            print("Fall down the crack and break every bone inyour body.")
                            time.sleep(1)
                            print("Your adventure has come to an end")
                    elif (river1=="build a bridge"):
                        print("The only wood around you is the trees.")
                        time.sleep(1)
                        print("So you start to chop down a tree with your axe...")
                        time.sleep(3)
                        print("You misjudge the height and weight of the tree.")
                        time.sleep(3)
                        print("It starts to fall over!")
                        time.sleep(3)
                        print("You don't get out of the way in time and the tree squashes you.")
                        time.sleep(1)
                        print("Your adventure has come to an end")
                    elif (river1=="jump over it"):
                        print("You walk back a bit.")
                        time.sleep(1)
                        print("Then stop, turn around and start to run towards the river.")
                        time.sleep(3)
                        print("You are runnung at full pace...")
                        time.sleep(3)
                        print("You jump!")
                        time.sleep(3)
                        print("You land on the sandy, other side of the river.")
                        time.sleep(3)
                        print("Because of the loose terrian, you slip and impale your head on a rock.")
                        time.sleep(1)
                        print("Your adventure has come to an end")
                elif (bunny1=="stay and ignore the bunny"):
                    print("You ignore the bunny and carry on filling your sack.")
                    time.sleep(3)
                    print("You feel a pain in your leg...")
                    time.sleep(3)
                    print("You look down to see the bunny munching on your leg.")
                    time.sleep(1)
                    print("You stab the bunny...")
                    time.sleep(1)
                    print("Its head falls off, but you still have a pain in your leg.")
                    time.sleep(1)
                    print("You finish collecting the berries and carry on walking")
                    time.sleep(3)
                    print("You walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("Untill you see the place you have been looking for.")
                    time.sleep(3)
                    print("Suddenly...")
                    time.sleep(3)
                    print("You fall down dead")
                    time.sleep(1)
                    print("Your adventure has come to an end")
            elif (eat1=="green"):
                print("You walk up to the bush with green berries.")
                time.sleep(1)
                print("You take a handful of green berries and put them in to your mouth...")
                time.sleep(3)
                print("You have eaten the wrong berries and fall down dead.")
                time.sleep(1)
                print("Your adventure has come to an end!")
        elif (movement=="run"):
            print("You start to run...")
            time.sleep(3)
            print("You trip and scrape your face off.")
            time.sleep(1)
            print("Your adventure has come to an end!")

elif (waydh=="on adventure"):
    print("Oh good, I love adventures!")
    time.sleep(1)
    direction1=input("Which way now, left or right?")
    if(direction1=="left"):
        print("Okay, to the left towards The Great Lake.")
        time.sleep(1)
        print("So you walked seveal miles to The Great Lake. But it does not go that smoothly.")
        time.sleep(1)
        print("Suddenly the ground shakes from the giant running towards you.")
        choice1=input("What do you want to do? Run the other way. Fight him. Run at him.")
        if (choice1=="run the other way"):
            print("You run the other way.")
            time.sleep(1)
            print("The giant is catching up...")
            time.sleep(1)
            print("The giant stood on you! Your adventure has come to an end.")
        elif (choice1=="fight him"):
            print("You draw your sword and you swing at his legs, making deep cuts.")
            time.sleep(3)
            print("But this does nothing. You stop and look for a weak spot. You spot a soft fleshy bit of skin, behind his knee cap.")
            time.sleep(3)
            print("You clamber up his leg, to the fleshy bit of skin and drive your sword in deep.")
            time.sleep(3)
            print("He falls to the ground, letting out an ear splitting scream.")
            time.sleep(3)
            print("After the death of the giant, you take his belongings, because he won't need them any more and carry on with your journey.")
            time.sleep(3)
            print("You walk a few more miles, it is getting dark now.")
            time.sleep(3)
            print("Eventually you get to The Great Lake; therefore you settle down for the night.")
            time.sleep(3)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("ZZZZZ")
            time.sleep(1)
            print("You hear a loud noise that startles you. You jump up, look around you, then you see it... A vampire!")
            time.sleep(1)
            choice2=input("You have to act fast. What do you do? Run in to the lake. Fight it.")
            if (choice2=="fight it"):
                print("The vampire is very close to you now so you draw and rasie you sword.")
                time.sleep(1)
                htkav=input("The vampire is with in arms reach, what do you do? Stab it in the face. Stab it in the heart.")
                if (htkav=="stab it in the face"):
                    print("You attempt does nothing; and the vampire drinks you blood.")
                    time.sleep(1)
                    print("Your adventure has come to an end.")
                elif (htkav=="stab it in the heart"):
                    print("You stab it though the heart.")
                    time.sleep(1)
                    print("Suddenly the vampire bursts in to a ball of blinding light")
                    time.sleep(1)
                    print("You shut your eyes untill Elrond taps you on the shoulder.")
                    time.sleep(1)
                    print("'Yes?' you say in return.")
                    time.sleep(1)
                    print("'Get up!' he says 'We have a long day ahead of us.'")
                    time.sleep(1)
                    print("You get up and walk around the lake.")
                    time.sleep(1)
                    print("You walk the rest of that day.")
                    time.sleep(1)
                    print("And the next day.")
                    time.sleep(1)
                    print("And the day after that.")
                    time.sleep(1)
                    print("You stop when you come to a sleeping wolf.")
                    time.sleep(1)
                    choice3=input("There is a sleeping wolf infront of you and just enough room to go around him. What do you do? Try and walk around him. Stab him in his sleep.")
                    if (choice3=="try and walk around him"):
                        print("He hears the shuffling of your feet and wakes up.")
                        time.sleep(1)
                        print("You freeze! But it is no luck, he bares his teeth, opens his mouth and rips you face off!")
                        time.sleep(1)
                        print("Your adventure has come to an end.")
                    elif (choice3=="stab him in his sleep"):
                        print("You draw your sword and bring it down on his neck, his head comes clean off and rolls along the floor for a little while, blood trailing after it.")
                        time.sleep(1)
                        os.system('cls')
                        print("After the third battle you walk for five days untill you get to a temple. The temple is tall, with pillars running each side.")
                        time.sleep(1)
                        print("You walk up to the door, but it does not open instead a voice sounds.")
                        time.sleep(1)
                        print("What has roots as nobody sees, Is taller than trees, Up, up it goes, And yet never grows?")
                        riddle1=input("Do you know the answer?")
                        if (riddle1=="mountain"):
                            print("The door opens, you walk forward to another door. A voice sounds again.")
                            time.sleep(1)
                            print("It cannot be seen, cannot be felt, Cannot be heard, cannot be smelt. It lies behind stars and under hills, And empty holes it fills. It comes first and follows after, Ends life, kills laughter.")
                            riddle2=input("Do you know the answer?")
                            if (riddle2=="dark"):
                                print("The door opens, you walk forward to another door. A voice sounds again.")
                                time.sleep(1)
                                print("You defeated three things so far, that is enough to make a triagram.")
                                triagram1=input("Can you work out the triagram...?")
                                if (triagram1=="gvw"):
                                    print("The door opens to reveal behind it a mountain load of treasure.")
                                    time.sleep(1)
                                    print("You and Elrond run in and grab what you want.")
                                    time.sleep(1)
                                    print("You come out with armfuls; and start to walk home")
                                    time.sleep(1)
                                    print("You have completed The Great Lake adventure!")
                                else:
                                    print("You here a cracking sound. Then a boulder falls down on top of you.")
                                    time.sleep(1)
                                    print("Your adventure has come to an end.")
                                    
                            else:
                                print("You here a cracking sound. Then a boulder falls down on top of you.")
                                time.sleep(1)
                                print("Your adventure has come to an end.")
                        else:
                            print("You here a cracking sound. Then a boulder falls down on top of you.")
                            time.sleep(1)
                            print("Your adventure has come to an end.")
                               
            elif(choice2=="run in to the lake"):
                print("You dart in to the lake.")
                time.sleep(1)
                print("A giant crab jumps up out of the water and pulls you under. This results in you drowning")
                time.sleep(1)
                print("Your adventure has come to an end.")
        elif (choice1=="run at him"):
            print("You run at him. Shouting your war cry, 'Arrrrrrrrgh!'")
            time.sleep(1)
            print("The Giant gets confused and panics, in the commotion you get a foot to the back and are shot in to a neighboring tree. SPLAT!!")
            time.sleep(1)
            print("Your adventure has come to an end!")
            

    elif (direction1=="right"):
        print("Okay, to the right towards Belzin forest")
        time.sleep(1)
        print("You start your journey to the Belzin forest")
        movement=input("Do you, run, or walk.")
        if (movement=="walk"):
            print("You have made a sensible decision; and slowly make your way to the Belzin forest")
            time.sleep(1)
            print("You have walked for several days and food has run out.")
            time.sleep(1)
            print("You see two bushes, one with yellow berries, the other with dark green berries.")
            eat1=input("Which one do you choose? Yellow. Green.")
            if (eat1=="yellow"):
                print("You walk up to the bush with yellow berries.")
                time.sleep(1)
                print("You take a handful of yellow berries and put them in to your mouth...")
                time.sleep(3)
                print("You have eaten the right berries and carry on with your journey.")
                time.sleep(1)
                print("You open your sack and start filling it with berries.")
                time.sleep(2)
                print("You hear a noise...")
                time.sleep(2)
                print("The bush starts to shake...")
                time.sleep(2)
                print("A big fluffy bunny with red eyes crawls out from the bush.")
                bunny1=input("What do you do? Run away. Stay and ignore the bunny.")
                if (bunny1=="run away"):
                    print("You run as fast as you can towards the end of the forest")
                    time.sleep(3)
                    print("You have escaped the bunny!")
                    time.sleep(1)
                    print("You start to slow down and gradualy come to a slow but sure walk")
                    time.sleep(2)
                    print("You walk for several days.")
                    time.sleep(1)
                    print("Untill you come to a river.")
                    river1=("What do you do? Go through the river. Build a bridge. Jump over.")
                    if(river1=="go through the river"):
                        print("You walk towards the river")
                        time.sleep(1)
                        print("Pull up your socks and wade in.")
                        time.sleep(3)
                        print("The water is cold, but you carry on going.")
                        time.sleep(3)
                        print("Eventually you get to the other side.")
                        time.sleep(3)
                        print("After the river you carry on walking untill you get to grass land.")
                        time.sleep(3)
                        print("Suddenly you come to a crack in the ground. You can not see the bottom, but you can see something running down the side of the hole.")
                        crack1=input("What do you do? Jump over the crack. Go down the crack. Give up all hope.")
                        if (crack1=="go down the crack"):
                            print("You lay on the ground, shuffle up to the crack and look down it.")
                            time.sleep(3)
                            print("The thing you saw was a ladder.")
                            time.sleep(3)
                            print("You grab it and swing yourself on to it.")
                            time.sleep(3)
                            print("You start to climb down the ladder...")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("And climb.")
                            time.sleep(1)
                            print("Untill you get to the bottom.")
                            time.sleep(3)
                            print("At the bottom you find...")
                            time.sleep(3)
                            os.system('cls')
                            maths1=input("This carved in to stone, 'If x=4, then what is y, 7x+3y=55' y=")
                            if (maths1=="7"):
                                print("The stone gives way, just enough for you to walk past it.")
                                time.sleep(3)
                                print("You walk past it.")
                                time.sleep(3)
                                print("But there is another stone.")
                                time.sleep(3)
                                print("and it says, 'You have come so far, but do you remember the way you came?'")
                                directionriddle=input("At the start of this adventure which way did you go? Left. Right. Straight on.")
                                if (directionriddle=="right"):
                                      print("The stone gives way completely, to reveal the tomb of your family.")
                                      time.sleep(3)
                                      print("You walk in and sit down making yourself comfortable.")
                                      time.sleep(3)
                                      print("You get up again and walk over to a coffin.")
                                      time.sleep(3)
                                      print("The plaque on it says, '",name,"Palm'")
                                      time.sleep(3)
                                      print("'I am named after my great father.' you say.")
                                      time.sleep(3)
                                      print("You smile.")
                                      time.sleep(3)
                                      print("Then you put you hand on his coffin...")
                                      time.sleep(3)
                                      print("A great flash of light surrounds you...")
                                      time.sleep(3)
                                      print("You close your eyes...")
                                      time.sleep(3)
                                      print("You feel like you are falling.")
                                      time.sleep(1)
                                      print("Faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("And faster.")
                                      time.sleep(1)
                                      print("Untill you suddenly stop an inch of the ground.")
                                      time.sleep(3)
                                      print("You have joined the after life.")
                                      time.sleep(1)
                                      print("To be continued.")
                                else:
                                    print("You hear a creaking sound...")
                                    time.sleep(3)
                                    print("Suddenly a massive body of water comes rushing towards you.")
                                    time.sleep(3)
                                    print("The water fills the whole crack and you drown!")
                                    time.sleep(1)
                                    print("Your adventure has come to an end")    
                                
                                
                            else:
                                print("You hear a creaking sound...")
                                time.sleep(3)
                                print("Suddenly a massive body of water comes rushing towards you.")
                                time.sleep(3)
                                print("The water fills the whole crack and you drown!")
                                time.sleep(1)
                                print("Your adventure has come to an end")
                        elif (crack1=="jump over crack"):
                            print("You stand on the edge of the crack and jump...")
                            time.sleep(3)
                            print("You don't jump far enough...")
                            time.sleep(3)
                            print("You land on the edge of the crack, slip and fall down it.")
                            time.sleep(1)
                            print("Your adventure has come to an end")
                        elif (crack1=="give up all hope"):
                            print("You sit down on the ground and do nothing.")
                            time.sleep(3)
                            print("Then you feel a sharp pain in your back.")
                            time.sleep(3)
                            print("You turn around to find the bunny ripping bits of flesh from your body.")
                            time.sleep(3)
                            print("You faint...")
                            time.sleep(3)
                            print("Fall down the crack and break every bone inyour body.")
                            time.sleep(1)
                            print("Your adventure has come to an end")
                    elif (river1=="build a bridge"):
                        print("The only wood around you is the trees.")
                        time.sleep(1)
                        print("So you start to chop down a tree with your axe...")
                        time.sleep(3)
                        print("You misjudge the height and weight of the tree.")
                        time.sleep(3)
                        print("It starts to fall over!")
                        time.sleep(3)
                        print("You don't get out of the way in time and the tree squashes you.")
                        time.sleep(1)
                        print("Your adventure has come to an end")
                    elif (river1=="jump over it"):
                        print("You walk back a bit.")
                        time.sleep(1)
                        print("Then stop, turn around and start to run towards the river.")
                        time.sleep(3)
                        print("You are runnung at full pace...")
                        time.sleep(3)
                        print("You jump!")
                        time.sleep(3)
                        print("You land on the sandy, other side of the river.")
                        time.sleep(3)
                        print("Because of the loose terrian, you slip and impale your head on a rock.")
                        time.sleep(1)
                        print("Your adventure has come to an end")
                elif (bunny1=="stay and ignore the bunny"):
                    print("You ignore the bunny and carry on filling your sack.")
                    time.sleep(3)
                    print("You feel a pain in your leg...")
                    time.sleep(3)
                    print("You look down to see the bunny munching on your leg.")
                    time.sleep(1)
                    print("You stab the bunny...")
                    time.sleep(1)
                    print("Its head falls off, but you still have a pain in your leg.")
                    time.sleep(1)
                    print("You finish collecting the berries and carry on walking")
                    time.sleep(3)
                    print("You walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("Etc.")
                    time.sleep(1)
                    print("And walk.")
                    time.sleep(1)
                    print("Untill you see the place you have been looking for.")
                    time.sleep(3)
                    print("Suddenly...")
                    time.sleep(3)
                    print("You fall down dead")
                    time.sleep(1)
                    print("Your adventure has come to an end")
            elif (eat1=="green"):
                print("You walk up to the bush with green berries.")
                time.sleep(1)
                print("You take a handful of green berries and put them in to your mouth...")
                time.sleep(3)
                print("You have eaten the wrong berries and fall down dead.")
                time.sleep(1)
                print("Your adventure has come to an end!")
        elif (movement=="run"):
            print("You start to run...")
            time.sleep(3)
            print("You trip and scrape your face off.")
            time.sleep(1)
            print("Your adventure has come to an end!")
    
elif(waydh=="lost"):
    print("The exit is that way. -->")

else:
    print("Uh, good bye!")
input("Press enter to exit.")
